version: "3.8"
services: 
  php-converter-api: 
    container_name: php-converter-api
    build: 
      context: ./converter-api
      target: php-converter-api
    ports: 
      - 8000:80
    volumes: 
      - ./converter-api:/var/www/html
      - ./converter-api/public:/var/www/html/public
    environment: 
      APP_NAME: Laravel
      APP_ENV: dev
      APP_KEY: base64:XfJMEWY4Y00O7TNw0oI9ND+1ijwiXu3r1m0NOZyJyp8=
      APP_DEBUG: true
      APP_INTERNAL_YOUTUBE_API: 'http://node-internal-youtube-api:7777'
      APP_URL: http://localhost:8000
      APP_ENCRYPT_DECRYPT_KEY: gdfgdf4g4fdg4fd44fs4e4zr4ezr44gvdgv4df4g4
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      QUEUE_CONNECTION: database
    depends_on: 
      - db
    networks: 
      - app_network

  website-front: 
    container_name: website-front
    build: 
      context: ./website-front
      target: website-front
    ports: 
      - 3000:80
    volumes: 
      - ./website-front:/var/www/html
      - ./website-front/public:/var/www/html/public
    environment: 
      APP_NAME: Easy Youtube
      APP_ENV: dev
      APP_KEY: base64:XfJMEWY4Y00O7TNw0oI9ND+1ijwiXu3r1m0NOZyJyp8=
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: 161.97.67.144
      DB_PORT: 5432
      DB_DATABASE: myvid
      DB_USERNAME: myvid
      DB_PASSWORD: WEuz7G8EUMlhF2Y
      QUEUE_CONNECTION: database
    depends_on: 
      - db
    networks: 
      - app_network

  php-processing-api: 
    container_name: php-processing-api
    build: 
      context: ./processing-api
      target: php-processing-api
    ports: 
      - 9999:80
    volumes: 
      - ./processing-api:/var/www/html
      - ./processing-api/public:/var/www/html/public
    environment: 
      APP_NAME: Laravel
      APP_ENV: dev
      APP_KEY: base64:XfJMEWY4Y00O7TNw0oI9ND+1ijwiXu3r1m0NOZyJyp8=
      APP_DEBUG: true
      APP_INTERNAL_YOUTUBE_API: 'http://node-internal-youtube-api:7777'
      APP_URL: http://localhost:8000
      APP_ENCRYPT_DECRYPT_KEY: gdfgdf4g4fdg4fd44fs4e4zr4ezr44gvdgv4df4g4
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      QUEUE_CONNECTION: database
    depends_on: 
      - db
    networks: 
      - app_network

  node-internal-youtube-api: 
    container_name: node-internal-youtube-api
    build: 
      context: ./internal-youtube-api
      target: node-internal-youtube-api
    ports: 
      - 7777:7777
    networks: 
      - app_network

  db: 
    image: postgres:15
    container_name: postgres-db-easy-youtu
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: 
      - db:/var/lib/postgresql/data
    networks: 
      - app_network

  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadmin-easy-youtu
    restart: always
    ports: 
      - "8888:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes: 
      - pgadmin:/var/lib/pgadmin*

networks: 
  app_network: 
    driver: bridge

volumes: 
  db: 
    external: true
  pgadmin: 
    external: true